#pragma once

enum TokenPrimaryType{
    TOKEN_ERROR,
    TOKEN_IDENTIFIER,
    TOKEN_KEYWORD,
    TOKEN_NUMBER,
    TOKEN_EOF,

    TOKEN_COUNT
};

static const char *TOKEN_PRIMARY_TYPE_STRING[] = {
    "TOKEN_ERROR",
    "TOKEN_IDENTIFIER",
    "TOKEN_KEYWORD",
    "TOKEN_NUMBER",
    "TOKEN_EOF",

    "TOKEN_COUNT"
};



enum TokenSecondaryType{
    TOKEN_NUMERIC_HEX,
    TOKEN_NUMERIC_BIN,
    TOKEN_NUMERIC_DEC,
    TOKEN_NUMERIC_OCT,
    TOKEN_NUMERIC_DOUBLE,
    
    TOKEN_IDENTIFIER,
    TOKEN_KEYWORD,
    TOKEN_NUMBER,
    TOKEN_EOF,

    TOKEN_COUNT
};